name: example
version: 1.0.0
author: "Sergey Penkovsky <sergey.penkovsky@gmail.com>"
homepage:

environment:
  sdk: ">=2.11.0-213.0.dev <2.12.0"


dependencies:
  dart_di:
    path: ../

dev_dependencies:
