name: dart_di
description: Experimental Dependency Injection library.
version: 0.0.1
author: Sergey Penkovsky <sergey.penkovsky@gmail.com>
homepage:

environment:
  sdk: ">=2.11.0-213.0.dev <2.12.0"

dependencies:
  meta: ^1.3.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety

  mockito: ^4.1.3
